/**
 * @file displaycontrol.h
 * @version 0.1
 * @date 11/04/2012
 * @author: Carlos Pereira Atencio
 * 
 * Library description comes here
 * 
 * This library has been developed to use a Processor Expert autogenerated
 * code from the GI2C1(I2C2:I2C_LDD) component.
 *************************************************************************** */

#ifndef DISPLAYCONTROL_H_
#define DISPLAYCONTROL_H_

#include "common.h"

void display_Init(void);
void display_SetTime(uint16 seconds);
void display_SetByte(byte value);
void display_SetDigit1(byte digit);
void display_SetDigit2(byte digit);
void display_SetDigit3(byte digit);
void display_SetDigit4(byte digit);
void display_SendI2C();
void display_FlashAll();
void display_FlashDigitl();
void display_FlashDigit2();
void display_FlashDigit3();
void display_FlashDigit4();
#endif /* DISPLAYCONTROL_H_ */
