/**
 * @file displaycontrol.h
 * @version 0.1
 * @date 30/04/2013
 * @author: Carlos Pereira Atencio
 * 
 * Library description comes here
 * 
 * This library has been developed to use a Processor Expert autogenerated
 * code from the GI2C1(I2C2:I2C_LDD) component.
 *************************************************************************** */

#ifndef DISPLAYCONTROL_H_
#define DISPLAYCONTROL_H_

#include "common.h"

void display_Init(void);
void display_SetUint16(uint16 value);
void display_SetByteLeft(uint8 value);
void display_SetByteRight(uint8 value);
void display_SetDigit1(uint8 digit);
void display_SetDigit2(uint8 digit);
void display_SetDigit3(uint8 digit);
void display_SetDigit4(uint8 digit);
void display_DisplayDigitl(void);
void display_DisplayDigit2(void);
void display_DisplayDigit3(void);
void display_DisplayDigit4(void);
void display_FlashAllDigits(void);
void display_AllDigitsOff(void);

#endif /* DISPLAYCONTROL_H_ */
