/**
 * @file joystickservo.h
 * @version 0.2
 * @date 24/05/2013
 * @author: Carlos Pereira Atencio
 *          Pawel
 * 
 * This library interfaces with the PWM internal peripheral and the data
 * processed by the joystick module. 
 * 
 * This library has been developed to use a Processor Expert autogenerated
 * code from the PWM1, and PWM2.
 *************************************************************************** */

#ifndef JOYSTICKSERVO_H_
#define JOYSTICKSERVO_H_

#include "common.h"

/* Function definitions */
uint16 js_JoystickToUs(uint16 joystick16BitRange);
void js_SetServoDutyUsX(uint16 us);
void js_SetServoDutyUsY(uint16 us);
inline uint16 js_GetXUs(void);
inline uint16 js_GetYUs(void);
void js_Move(void);
void js_ServoStart(void);
void js_ServoStop(void);
void js_ServoCentre(void);
void js_ServoInit(void);
uint16 js_DifficultyAddOffsetX(uint16 joystickXOp);
uint16 js_DifficultyAddOffsetY(uint16 joystickYOp);
uint8 js_GetDifficultyLevel(void);

#endif /* JOYSTICKSERVO_H_ */
