/**
 * @file joystickservo.h
 * @version 0.1
 * @date 23/05/2013
 * @author: Carlos Pereira Atencio
 *          Pawel
 * 
 * This library interfaces with the PWM internal peripheral and the data
 * coming from the ADC internal peripheral. 
 * 
 * This library has been developed to use a Processor Expert autogenerated
 * code from the PWM1, PWM2, and ADC1 components.
 *************************************************************************** */

#ifndef JOYSTICKSERVO_H_
#define JOYSTICKSERVO_H_

#include "common.h"

/* Global array containing ADC readouts (2 members)*/
uint16 ADC_READOUT[AD1_CHANNEL_COUNT];

/* Function definitions */
uint16 AdcRead(void);
uint16 js_CalibrateXMin(void);
uint16 js_CalibrateXCentre(void);
uint16 js_CalibrateXMax(void);
uint16 js_CalibrateYMin(void);
uint16 js_CalibrateYCentre(void);
uint16 js_CalibrateYMax(void);
uint16 ConditionADCx(uint16 ADC_X);
uint16 ConditionADCy(uint16 ADC_Y);
uint16 js_AdcToUsX(uint16 adc);
uint16 js_AdcToUsY(uint16 adc);
void js_SetServoDutyUsX(uint16 us);
void js_SetServoDutyUsY(uint16 us);
void js_Move(void);

#endif /* JOYSTICKSERVO_H_ */
