/**
 * @file scheduler.h
 * @version 0.1
 * @date 02/05/2013
 * @author: Carlos Pereira Atencio
 * 
 * This header file contains the code that defines and assignees the functions
 * to be scheduled by the FreeRTOS system. This is not an scheduler on its 
 * own right and just configures the FreeRTOS scheduler.
 * 
 * The software has been designed this way to hide a lot of the complexity
 * of the RTOS, and to reduce the amount of code introduced within the source
 * files automatically generated by the Processor Expert FreeRTOS component.
 *************************************************************************** */

#ifndef SCHEDULER_H_
#define SCHEDULER_H_

void createTasks();

#endif /* SCHEDULER_H_ */
