/**
 * @file servocontrol.h
 * @version 0.1
 * 
 * This library interfaces with the PWM internal peripheral.
 * 
 * This library has been developed to use a Processor Expert autogenerated
 * code from the PWM1, and PWM2.
 *************************************************************************** */

#ifndef SERVOCONTROL_H_
#define SERVOCONTROL_H_

#include "common.h"

void servo_Init(void);
void servo_Start(void);
void servo_Stop(void);
void servo_Centre(void);
uint16 servo_16BitsToUs(uint16 Full16BitRange);
void servo_Duty16BitX(uint16 Full16BitRange);
void servo_Duty16BitY(uint16 Full16BitRange);

#endif /* SERVOCONTROL_H_ */
